name: VKS Cluster Create

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:                                                    # Global Environment Variable 
  SUPERVISOR_IP: "192.168.80.6"        
  VCF_CLI_VSPHERE_USERNAME: "administrator@vsphere.local"
  VCF_CLI_VSPHERE_PASSWORD: ${{ secrets.VCF_CLI_VSPHERE_PASSWORD }}
  WORKLOAD_CLUSTER_NAME: "github-check"
  VSPHERE_NAMESPACE: "github-actions"
  
jobs:
  Downloading-Plugin:                       # name of the job
    runs-on: arc-runner-vks                 # Runer location
    env:
      KUBECTL_VERSION: "v1.34.0"            # local Environment variable 
      VCF_CLI_VERSION: "v9.0.1"
    
    steps:
    
      - name: Cache plugins
        id: cache-plugin
        uses: actions/cache@v4
        with:
          path: ~/.kube/plugins/my-plugin                           # Path where plugin is stored
          key: plugin-${{ hashFiles('**/plugin-version.txt') }}     # Stable key (e.g., version file)

      - name: Download plugin if cache miss
        if: steps.cache-plugin.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.kube/plugins/my-plugin
          curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
          curl -LO "https://packages.broadcom.com/artifactory/vcf-distro/vcf-cli/linux/amd64/${VCF_CLI_VERSION}/vcf-cli.tar.gz"
          chmod +x kubectl; cp kubectl ~/.kube/plugins/my-plugin                                                                      
          tar -xvf vcf-cli.tar.gz; mv vcf-cli-linux_amd64 vcf; chmod +x vcf; cp vcf ~/.kube/plugins/my-plugin
          sudo cp ~/.kube/plugins/my-plugin/kubectl /usr/local/bin; sudo cp ~/.kube/plugins/my-plugin/vcf /usr/local/bin
          vcf context create supervisor-login --endpoint ${SUPERVISOR_IP} --insecure-skip-tls-verify --username ${VCF_CLI_VSPHERE_USERNAME} --type k8s 
          cp -r ~/.config ~/.kube/plugins/my-plugin
          cp -r ~/.kube/config ~/.kube/plugins/my-plugin
          echo "v1.0" > plugin-version.txt  # For key stability

  Workload-Creation:                          # name of the job
    needs: Downloading-Plugin                 # job dependecy
    runs-on: arc-runner-vks                   # Runer location
    
    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache plugin
        uses: actions/cache@v4
        with:
          path: ~/.kube/plugins/my-plugin
          key: plugin-${{ hashFiles('**/plugin-version.txt') }}
          restore-keys: plugin-  # Fallback to similar versions

      - name: Logging to Cluster
        run: |
           sudo cp ~/.kube/plugins/my-plugin/kubectl /usr/local/bin; sudo cp ~/.kube/plugins/my-plugin/vcf /usr/local/bin
           cp ~/.kube/plugins/my-plugin/config ~/.kube
           cp -r  ~/.kube/plugins/my-plugin/.config ~
           vcf context refresh supervisor-login
           kubectl config use-context supervisor-login
          
      - name: Creating the Cluster
        run: |     
          sed -i "s/WORKLOAD_CLUSTER_NAME/${WORKLOAD_CLUSTER_NAME}/g" clustercreate.yaml
          sed -i "s/VSPHERE_NAMESPACE/${VSPHERE_NAMESPACE}/g" clustercreate.yaml
          kubectl apply -f clustercreate.yaml

  Checking-Cluster-Status:
    needs: Workload-Creation
    timeout-minutes: 15
    runs-on: arc-runner-vks

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache plugin
        uses: actions/cache@v4
        with:
          path: ~/.kube/plugins/my-plugin
          key: plugin-${{ hashFiles('**/plugin-version.txt') }}
          restore-keys: plugin-  # Fallback to similar versions

      - name: Cache vcf plugins
        uses: actions/cache@v4
        with:
          path: ~/.config  # Path where plugin is stored
          key: vcfplugin-${{ hashFiles('**/vcfplugin-version.txt') }}  # Stable key (e.g., version file)
          restore-keys: vcfplugin-

      - name: Creating the VCF Context 
        run: |
          chmod +x ./scripts/machine-status.sh
          sudo cp ~/.kube/plugins/my-plugin/kubectl /usr/local/bin; sudo cp ~/.kube/plugins/my-plugin/vcf /usr/local/bin
          vcf context create supervisor-login --endpoint ${SUPERVISOR_IP} --insecure-skip-tls-verify --username ${VCF_CLI_VSPHERE_USERNAME} --type k8s --skip-create-related-contexts
          vcf context use supervisor-login

      - name: Status Check for Workload Cluster
        shell: bash
        run: ./scripts/machine-status.sh
        timeout-minutes: 15
