name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: arc-runner-vks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl CLI 
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          mv kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Install VCF CLI
        run: |
          wget "https://packages.broadcom.com/artifactory/vcf-distro/vcf-cli/linux/amd64/v9.0.1/vcf-cli.tar.gz"
          tar -xvf vcf-cli.tar.gz
          sudo mv vcf-cli-linux_amd64 /usr/local/bin/vcf
          vcf version

